### ISSUE TITLE
As a user, I want to be able to create a lobby in order to create a group for playing.

### ISSUE THREAD

**Issue by luis-tm** [sopra-fs22-group-16/sopra-fs22-group-16-server#1]
## Acceptance criteria
- [x] A user can click a button on the home page of the game to create a new lobby.
- [x] By clicking the button, the user is redirected to a new page where they can pick the settings name of the lobby, gamemode and visibility.
- [x] The creator of a lobby can get a code which can be shared to invite other players.
- [x] Only the creator of a lobby can get the codes to share a lobby.
- [x] It is possible to see how many people are in the lobby and it is not possible to enter the lobby if it is full.
- [x] The lobby owner can then go between the settings page and the lobby page without disbanding the lobby.
- [x] The lobby owner can press a button to get to the lobby page where they see the settings of the lobby and the users in the lobby.
## Development tasks
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#28
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#29
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#30
- [x] sopra-fs22-group-16/sopra-fs22-group-16-server#140
- [x] sopra-fs22-group-16/sopra-fs22-group-16-server#141
- [x] sopra-fs22-group-16/sopra-fs22-group-16-server#142
- [x] sopra-fs22-group-16/sopra-fs22-group-16-server#143
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#68
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#82
