### ISSUE TITLE
As a player, if it is my turn, I want to give my units movements commands in order to move them around the battlefield.

### ISSUE THREAD

**Issue by luis-tm** [sopra-fs22-group-16/sopra-fs22-group-16-server#13]
## Acceptance criteria
- [x] By clicking on the move action of one unit, the possible squares on the map the unit can go are highlighted.
- [x] When clicking a possible square, the unit is placed on the new position.
- [x] If the player clicks on an invalid square, no action is taken.
- [x] A unit is able to move a number of tiles on the map up to its movement range.
- [x] When moving units on the map, the changes are communicated to the server.
## Development tasks
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#49
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#48
- [x] sopra-fs22-group-16/sopra-fs22-group-16-server#185
- [x] sopra-fs22-group-16/sopra-fs22-group-16-server#187
- [x] sopra-fs22-group-16/sopra-fs22-group-16-server#189
- [x] sopra-fs22-group-16/sopra-fs22-group-16-server#188
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#123
