### ISSUE TITLE
As a creator of a lobby, I want to be able to change the name, the gameMode, the gameType, and the visibility of the lobby.

### ISSUE THREAD

**Issue by luis-tm** [sopra-fs22-group-16/sopra-fs22-group-16-server#131]
## Acceptance criteria
- [x] It is possible to change the visibility of a lobby to make it private or public.
- [x] The lobby is given a unique automatically generated name.
- [x] The creator of the lobby can change the name of the lobby.
- [x] The creator of the lobby can change the gameMode and the gameType.
- [x] Players who are not host of a lobby cannot change the properties of a lobby.
## Development tasks
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#32
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#33
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#34
- [x] sopra-fs22-group-16/sopra-fs22-group-16-server#150
- [x] sopra-fs22-group-16/sopra-fs22-group-16-server#151
- [x] sopra-fs22-group-16/sopra-fs22-group-16-server#230
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#84
