### ISSUE TITLE
As creator of a lobby, I want to be able to leave the lobby.

### ISSUE THREAD

**Issue by luis-tm** [sopra-fs22-group-16/sopra-fs22-group-16-server#132]
## Acceptance criteria
- [x] The user who created the lobby can leave it if the game has not started.
- [x] If the user who created the lobby leaves, a user in the lobby is chosen to be the new creator of the lobby.
- [x] If the user who created the lobby leaves, and no users are left in it, the lobby is removed.
## Development tasks
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#35
- [x] sopra-fs22-group-16/sopra-fs22-group-16-server#153
- [x] sopra-fs22-group-16/sopra-fs22-group-16-server#154
- [x] #215
