### ISSUE TITLE
As a player, I want to have a name in a lobby in order to identify myself.

### ISSUE THREAD

**Issue by luis-tm** [sopra-fs22-group-16/sopra-fs22-group-16-server#133]
## Acceptance criteria
- [x] The users in the lobby are given a unique username for the duration of the game.
- [x] The users in the lobby can change their username but it has to be unique.
## Development tasks
- [x] sopra-fs22-group-16/sopra-fs22-group-16-server#144
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#31
- [x] sopra-fs22-group-16/sopra-fs22-group-16-server#146
