### ISSUE TITLE
As a player, if it is my turn, I want to give my units attack commands if they are close enough to an enemy unit in order to fight the enemy units.

### ISSUE THREAD

**Issue by luis-tm** [sopra-fs22-group-16/sopra-fs22-group-16-server#14]
## Acceptance criteria
- [x] By clicking on the attack action of one unit, the possible units which can be attacked are highlighted.
- [x] If the player choses an invalid square, no action is taken.
- [x] When choosing to attack a unit, a battle happens between the two units: depending on the attack and defence of both units, their health is updated.
- [x] If the health of a unit is reduced below 1 the unit dies and is removed from the game.
- [x] After an attack, if the units have still health, the attacker is placed on its initial square.
- [x] A unit is able to attack a hostile unit if it is within its attack range, which reduces the health of the hostile unit.
- [x] A unit is able to reduce the incoming damage with a higher defence stat.
- [x] When the health of a unit changes, this it is communicated to the server.
## Development tasks
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#50
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#51
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#52
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#53
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#54
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#55
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#56
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#57
- [x] sopra-fs22-group-16/sopra-fs22-group-16-server#198
- [x] sopra-fs22-group-16/sopra-fs22-group-16-server#200
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#163
