### ISSUE TITLE
As a player, I want to finish my turn after I have executed a command with all my units, in order to continue the game.

### ISSUE THREAD

**Issue by luis-tm** [sopra-fs22-group-16/sopra-fs22-group-16-server#15]
## Acceptance criteria
- [x] The players can use each unit they have on the map once.
- [x] When no unit of the player can perform another action, the turn of the team ends, and it starts the turn of the other team.
- [x] When changing the turn, a message is displayed, notifying it.
## Development tasks
- [x] sopra-fs22-group-16/sopra-fs22-group-16-server#203
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#59
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#60
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#61
- [x] sopra-fs22-group-16/sopra-fs22-group-16-server#207
- [x] #208
