### ISSUE TITLE
As the winner of a game, I want to be declared so, in order to finish the game.

### ISSUE THREAD

**Issue by luis-tm** [sopra-fs22-group-16/sopra-fs22-group-16-server#16]
## Acceptance criteria
- [x] When all units of a team have been destroyed, that team has lost.
- [x] A notification is displayed, announcing the winner of the game.
- [x] Store the result to enable the creation of statistics, e.g. a leader board.
## Development tasks
- [x] sopra-fs22-group-16/sopra-fs22-group-16-server#209
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#62
- [x] sopra-fs22-group-16/sopra-fs22-group-16-server#212
