### ISSUE TITLE
As a user, I want to be able to surrender in order to finish the game prematurely.

### ISSUE THREAD

**Issue by luis-tm** [sopra-fs22-group-16/sopra-fs22-group-16-server#17]
## Acceptance criteria
- [x] During the entire game, all players in a game can click a button to surrender.
- [x] If all players of a team click the surrender button, the game is finished, and the team who clicked it loses the game.
- [x] A notification is displayed, announcing the winner of the game.
- [x] If a player disconnects or loses connection for an predefined amount of time, the player automatically surrenders.

## Development tasks
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#110
- [x] sopra-fs22-group-16/sopra-fs22-group-16-server#257
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#109
