### ISSUE TITLE
As a user, I want to be able to play another game with the same players after finishing one.

### ISSUE THREAD

**Issue by luis-tm** [sopra-fs22-group-16/sopra-fs22-group-16-server#21]
## Acceptance criteria
- [x] The menu displayed after finishing a game has the button “play again”.
- [x] Pressing the "play again" button returns the player back to the lobby
- [x] All players are not ready when returning to the lobby

## Development tasks
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#186
- [x] sopra-fs22-group-16/sopra-fs22-group-16-server#275
- [x] sopra-fs22-group-16/sopra-fs22-group-16-server#346
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#185
