### ISSUE TITLE
As a user, I want to be able to see information about the match over time after it finished, in order to get an overview of the match and get better at the game.

### ISSUE THREAD

**Issue by luis-tm** [sopra-fs22-group-16/sopra-fs22-group-16-server#22]
## Acceptance criteria
- [x] The menu displayed after finishing a game has a button “statistics”.
- [x] By clicking the button, a new screen is displayed with different plots and tables which give information  about the finished game.
- [x] It is also possible to continue a game or go back to the home page in the lobby screen.

## Development tasks
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#114
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#115
- [x] sopra-fs22-group-16/sopra-fs22-group-16-server#260
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#112
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#113
