### ISSUE TITLE
As a guest, I want to register as a user with my chosen credentials (username and password that are both not empty) in order to keep track of my wins and losses, ranked score and user services exclusively available to registered users.

### ISSUE THREAD

**Issue by luis-tm** [sopra-fs22-group-16/sopra-fs22-group-16-server#23]
## Acceptance criteria
- [x] Upon successful registration, the user is redirected to their personal profile.
- [x] The guest is able to log in as many times as they want to enter their personal profile.
- [x] The username of a user has to be unique.
- [x] The personal profile contains the user information.
- [x] The username chosen by the user is automatically used in their games.
- [x] The username of registered users have precedence in a lobby over the chosen username of unregistered users.

## Development tasks - Server
- [x] sopra-fs22-group-16/sopra-fs22-group-16-server#326
- [x] sopra-fs22-group-16/sopra-fs22-group-16-server#340
- [x] sopra-fs22-group-16/sopra-fs22-group-16-server#341
- [x] #362

## Development tasks - Client
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#147
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#177
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#180
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#181
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#182
- [x] #360
