### ISSUE TITLE
As a registered user, I want to update my personal information.

### ISSUE THREAD

**Issue by luis-tm** [sopra-fs22-group-16/sopra-fs22-group-16-server#24]
## Acceptance criteria
- [x] In the personal profile of a register user there is a button to update the data.
- [x] The registered user cannot change their username to an existing one.
- [x] When changing the username, all the data referred to that attribute is updated (e.g. the rank).
- [x] By clicking this button, the data which is possible to change is highlighted and the user can change the values. This changes can be confirmed with another button.
## Development tasks - Server
- [x] sopra-fs22-group-16/sopra-fs22-group-16-server#330
## Development tasks - Client
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#178
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#179
