### ISSUE TITLE
As a user, I want to look at a leader board which displays the top registered users.

### ISSUE THREAD

**Issue by luis-tm** [sopra-fs22-group-16/sopra-fs22-group-16-server#25]
## Acceptance criteria
- [x] On the home page there is a button to see the leader board.
- [x] By clicking the button, a leader board is displayed showing the top registered users.
- [x] The list can be sorted by wins, losses, or rank score.

## Development tasks - Server
- [x] sopra-fs22-group-16/sopra-fs22-group-16-server#335
## Development tasks - Client
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#166
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#167
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#168
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#171
