### ISSUE TITLE
As a player of a lobby, I want to start the game if the lobby is completely full in order to play.

### ISSUE THREAD

**Issue by luis-tm** [sopra-fs22-group-16/sopra-fs22-group-16-server#3]
## Acceptance criteria
- [x] Each user in the lobby can click a button with which he can switch between ready and not ready.
- [x] If each user in the lobby is ready for 10 continuous seconds the game is automatically started.
- [x] When the timer runs out, all the players in the lobby are redirected to a new page where the game takes place.
## Development tasks
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#41
- [x] sopra-fs22-group-16/sopra-fs22-group-16-server#165
- [x] sopra-fs22-group-16/sopra-fs22-group-16-server#167
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#42
- [x] sopra-fs22-group-16/sopra-fs22-group-16-server#168
