### ISSUE TITLE
As a registered user, my username should have precedence over unregistered users as I choose that name when registering

### ISSUE THREAD

**Issue by apple00juice** [sopra-fs22-group-16/sopra-fs22-group-16-server#307]
## Acceptance criteria
- [x] When a registered user joins a lobby, the names of users already in the lobby need to be adjusted to allow for the registered user.

## Development tasks - Server
- [x] sopra-fs22-group-16/sopra-fs22-group-16-server#312
- [x] sopra-fs22-group-16/sopra-fs22-group-16-server#321
## Development tasks - Client
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#156
