### ISSUE TITLE
As a registered user, I want to user my credentials to enter a game or lobby in order to use with my username and ranked information

### ISSUE THREAD

**Issue by apple00juice** [sopra-fs22-group-16/sopra-fs22-group-16-server#349]
## Acceptance criteria
- [x] As a registered user, when joining a game I want to use my credentials to join the lobby/game
- [x] As a registered user, I don't want to loose my credentials (get logged out) when leaving a lobby/game

## Development tasks - Server
- [ ]

## Development tasks - Client
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#157
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#160
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#158
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#159
