### ISSUE TITLE
As a user, I want to see that the game ended in a draw in order to know how the game eneded

### ISSUE THREAD

**Issue by apple00juice** [sopra-fs22-group-16/sopra-fs22-group-16-server#368]
## Acceptance criteria
- [x] When the game ends in a draw I want to see that the game ended in a draw
- [x] When a ranked game ends in a draw the losses wins and rankedScore should not change

## Development tasks - Server
- [x] sopra-fs22-group-16/sopra-fs22-group-16-server#369

## Development tasks - Client
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#195
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#196
