### ISSUE TITLE
As a user, I want to use a code in order to invite other users to enter a lobby that already exists.

### ISSUE THREAD

**Issue by luis-tm** [sopra-fs22-group-16/sopra-fs22-group-16-server#4]
## Acceptance criteria
- [x] The home page of the game allows a user to click a button to join a lobby by entering a code shared by the creator of the lobby.
- [x] It is not possible to enter a lobby by entering an incorrect code.
- [x] It is not possible to enter a lobby if the code has not been generated yet.
## Development tasks
- [x] sopra-fs22-group-16/sopra-fs22-group-16-server#159
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#39
- [x] sopra-fs22-group-16/sopra-fs22-group-16-server#161
- [x] sopra-fs22-group-16/sopra-fs22-group-16-server#162
