### ISSUE TITLE
As a user, I want to be able to find a public lobby in order to join a game.

### ISSUE THREAD

**Issue by luis-tm** [sopra-fs22-group-16/sopra-fs22-group-16-server#5]
## Acceptance criteria
- [x] A user can click a button on the home page of the game, which redirects to a page with a list of public not full lobbies.
- [x] For each displayed lobby its name, current game mode, players in the lobby and maximum number of players is displayed
- [x] By clicking on one of the lobbies, the user is redirected to the lobby screen of this lobby.
- [x] Upon failure to join the lobby, an error is displayed, and the user is redirected (back) to the lobby list.
## Development tasks
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#36
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#37
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#38
- [x] sopra-fs22-group-16/sopra-fs22-group-16-server#158
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#83
