### ISSUE TITLE
As a creator of a lobby, I want to share a QR – Code in order to invite other players to join me in my lobby.

### ISSUE THREAD

**Issue by luis-tm** [sopra-fs22-group-16/sopra-fs22-group-16-server#6]
## Acceptance criteria
- [x] The lobbies have a button only visible for the creators, which enables them to create a QR – code.
- [x] By scanning the QR – code associated with a lobby, a user is redirected to this lobby in order to join this game.
- [x] If the lobby is full, scanning the QR – code the user doesn’t join the lobby and is redirect to the home screen and an error is shown.
## Development tasks
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#43
- [x] sopra-fs22-group-16/sopra-fs22-group-16-server#170
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#44
- [x] sopra-fs22-group-16/sopra-fs22-group-16-server#173
