### ISSUE TITLE
As a player, I want to be able to choose a game with a 1vs1 map in order to play.

### ISSUE THREAD

**Issue by luis-tm** [sopra-fs22-group-16/sopra-fs22-group-16-server#7]
## Acceptance criteria
- [x] The game has to display the generated map on the screen.
- [x] The size of the map fits 2 players.
- [x] The generated map has a grid structure which can contain information about the tiles (grass, river, mountain, etc).
- [x] The different squares of the map can have information about a unit which is on it.
## Development tasks
- [x] sopra-fs22-group-16/sopra-fs22-group-16-server#174
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#45
- [x] sopra-fs22-group-16/sopra-fs22-group-16-server#175
