### ISSUE TITLE
As a player, I want to have units on the map during a 1vs1 game in order to play.

### ISSUE THREAD

**Issue by luis-tm** [sopra-fs22-group-16/sopra-fs22-group-16-server#8]
## Acceptance criteria
- [x] When starting a game the units of each player are placed clumped together but apart from hostile units on the map.
## Development tasks
- [x] sopra-fs22-group-16/sopra-fs22-group-16-server#177
- [x] sopra-fs22-group-16/sopra-fs22-group-16-server#178
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#46
- [x] sopra-fs22-group-16/sopra-fs22-group-16-server#180
